### PR TITLE
ci: introduce terraform 1.7 in CI workflows

### PR DESCRIPTION
**Pull request by FoSix**
## Description

Add Terraform 1.7 into workflows

## Motivation and Context

Since this version of Terraform is officially supported by the modules, test should be run using this version. 

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by FoSix** [comment]
/plan paths="examples/common_vmseries examples/common_vmseries_and_autoscale examples/dedicated_vmseries examples/dedicated_vmseries_and_autoscale examples/gwlb_with_vmseries examples/standalone_panorama examples/standalone_vmseries examples/test_infrastructure"

**Comment by FoSix** [comment]
/idempotence paths="examples/common_vmseries examples/common_vmseries_and_autoscale examples/dedicated_vmseries examples/dedicated_vmseries_and_autoscale examples/gwlb_with_vmseries examples/standalone_panorama examples/standalone_vmseries examples/test_infrastructure"

**Review by sebastianczech — APPROVED** [review]

**Pull request merged**
